<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/css" href="style.css"?>
<!DOCTYPE store [
    <!ELEMENT store (product+)>
    <!ELEMENT product (name, category,price)>
    <!ELEMENT name (#PCDATA)>
    <!ELEMENT category (#PCDATA)>
    <!ELEMENT price (#PCDATA)>
    <!ENTITY Byn "BYN" >
]>
<store>
   <product>
        <name>Айфон 14</name>
        <category>Мобильники</category>
        <price>2666,00 BYN</price>
    </product>
    <product>
        <name>АСУС супербук с22</name>
        <category>Ноутбуки</category>
        <price>5525,00 BYN</price>
    </product>
    <product>
        <name>Холодильник</name>
        <category>Бытовая техника</category>
        <price>2899,00 BYN</price>
    </product>
    <product>
        <name>Телевизор</name>
        <category>Электроника</category>
        <price>4799,00 BYN</price>
    </product>
    <product>
        <name>Микроволновка</name>
        <category>Бытовая техника</category>
        <price>699,00 BYN </price>
    </product>
</store>